### ISSUE TITLE
combine_docfiles.py fails if the license comment is missing in Terraform configuration files

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-module-template#16]
https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/pull/1#discussion_r280937156

**Comment by aaron-lane** [comment]
`terraform-docs` outputs our license comment along with the inputs table and the outputs table. If that license comment is not present in the module files then `combine_docfiles.py` will fail to generate the documentation for the particular module. The work-around is to add the missing license comment to the files. `make check_headers` will indicate which files are missing headers.

**Comment by morgante** [comment]
Is this a bug? We expect all files to have a license header.

**Comment by aaron-lane** [comment]
It is indeed a bug. There is a separate check which will identify files without the license header. The documentation generation task should not fail because of an absent header.

**Comment by morgante** [comment]
Ok, let's mark this as a P4 then since fixing bugs in non-compliant repos aren't our main target.

**Comment by ivankorn** [comment]
@aaron-lane, this bug seems to be no longer relevant, as we don't use the script since [ terraform_docs.sh](https://github.com/terraform-google-modules/terraform-google-module-template/pull/26)  PR is merged

**Comment by aaron-lane** [comment]
Fixed by #26.
