### ISSUE TITLE
Add pre-commit-terraform

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-module-template#23]
[terraform-docs does not currently support Terraform 0.12](https://github.com/segmentio/terraform-docs/issues/62).

[pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform) has implemented a workaround for using `terraform-docs` with Terraform 0.12. This seems like a good excuse to integrate the [pre-commit framework](https://pre-commit.com) in to our modules.

Add `pre-commit-terraform` to the module template and replace the existing usage of `terraform-docs` with the `terraform_docs` hook. This should include removing the logic within [test/make.sh](https://github.com/terraform-google-modules/terraform-google-module-template/blob/master/terraform-google-%7B%7Bcookiecutter.module_name%7D%7D/test/make.sh#L73-L87), the action in [Makefile](https://github.com/terraform-google-modules/terraform-google-module-template/blob/master/terraform-google-%7B%7Bcookiecutter.module_name%7D%7D/Makefile#L33-L52), and the package in the [Dockerfile](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/concourse/build/Dockerfile.lint#L31-L33).

**Comment by metmajer** [comment]
@aaron-lane will keep you posted about any updates on Terraform 0.12 support in terraform-docs

**Comment by aaron-lane** [comment]
Great, thanks @metmajer!
