### ISSUE TITLE
Import behavior changes from IAM test suite

### ISSUE THREAD

**Issue by jeffmccune** [terraform-google-modules/terraform-google-module-template#29]
Minor behavior changes to integration tests were made in https://github.com/terraform-google-modules/terraform-google-iam/pull/34.

 * [ ] Fix false positive failures in trap handler
 * [ ] Display kitchen full log in trap handler.
 * [ ] Changes to find_files to get lint tests passing
 * [ ] Fix `make check_terraform` with 0.12, requires terraform init now

**Comment by aaron-lane** [comment]
Fixed by #30.
