### ISSUE TITLE
Fix Test Suite

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-google-modules/terraform-google-module-template#34]
Running `make tests` yields errors on `master`:

```
Error: "ci-module_test" name must be 4 to 30 characters with lowercase and uppercase letters, numbers, hyphen, single-quote, double-quote, space, and exclamation point.

  on .terraform/modules/project/terraform-google-modules-terraform-google-project-factory-f93d3cd/modules/core_project_factory/main.tf line 126, in resource "google_project" "main":
 126: resource "google_project" "main" {


make[1]: *** [docker_test_prepare] Error 1
```

It looks like https://github.com/terraform-google-modules/terraform-google-module-template/blob/master/terraform-google-%7B%7Bcookiecutter.module_name%7D%7D/test/setup/main.tf#L21 is trying to replace hyphens with underscores, when it should be the other way around.

**Comment by apeabody** [comment]
Fixed in https://github.com/terraform-google-modules/terraform-google-module-template/pull/64
