### ISSUE TITLE
Github token reference interpreted as a cookiecutter variable.

### ISSUE THREAD

**Issue by danistrebel** [terraform-google-modules/terraform-google-module-template#51]
Looks like cfcb92c500fd3cfdeae6c9e648478d10a015f500 broke the cookiecutter template because the Github token reference `${{ secrets.GITHUB_TOKEN }}` is interpreted as a cookiecutter variable.

**Comment by bharathkkb** [comment]
Thanks for the report @danistrebel 
Looks like [escaping](https://jinja.palletsprojects.com/en/3.0.x/templates/#escaping) maybe a solution. Could you try that out? Also happy to review a PR.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-module-template/pull/52
