### ISSUE TITLE
Add `.terraform.lock.hcl` files to the initial `.gitignore` file

### ISSUE THREAD

**Issue by daniel-cit** [terraform-google-modules/terraform-google-module-template#54]
a new section with 

```shell
# Terraform lock file
**/.terraform.lock.hcl
```

Should be added to terraform section of the initial `.gitignore` file

https://github.com/terraform-google-modules/terraform-google-module-template/blob/38860752754b0ab80629119947232830e734930a/terraform-google-%7B%7Bcookiecutter.module_name%7D%7D/.gitignore#L24-L30

The file is created automatically since TF 0.14

**Comment by apeabody** [comment]
Added in https://github.com/terraform-google-modules/terraform-google-module-template/pull/53
